Highlight current menu depending on scroll
etalab/catalogage-donnees pull request #228
Opened 2022-05-10 07:20 UTC by lpoujade

Closes #217

Adapté pour svelte v3 depuis https://github.com/sveltejs/v2.svelte.dev/blob/master/src/routes/guide/index.html

J'ai pu lancer `prettier`, mais les test ne fonctionnent pas (probablement parce que je n'ai lancé que la stack docker), et les check non plus (ma version de typescript est peut être trop élevé. mais au début j'ai quand même `All matched files use Prettier code style!`)

2022-05-10 09:22 UTC, Volubyl requested changes
Dans l'ensemble cette PR est assez :ok_hand: et d'ailleurs merci pour cette contribution !

Une petite demande, si tu fait un `make check`, il y a quelques warnings levés par svelte. Il y en avait déja avant (il faudrait que je m'en occupe :thinking: ) mais les changements apportés par ta PR en ont ajoutés de nouveaux.

Pourrais-tu essayer de les corriger ?

Merci!

2022-05-10 09:22 UTC, Volubyl commented on client/src/lib/components/DatasetFormLayout/DatasetFormLayout.svelte
> +  let container = undefined;
Est-ce qu'il serait possible d'améliorer le typage de ces variables ?

Svelte/Ts n'a pas trop de soucis à inférer le type quand il s'agit de chose comme ceci `let foo = "" ` là il pourra déterminer que `foo` est de type `string`

Par contre avec `let tata = undefined` et il va considérer que tata est `any` de manière implicite J'aimerais qu'on réduise (le plus possible) les `any` implicites parce que je trouve qu'on perd un peu l'intérêt du typage

2022-05-10 09:22 UTC, Volubyl commented on client/src/lib/components/DatasetFormLayout/DatasetFormLayout.svelte
>  <script>
Oupsy c'était un oubli de ma part mais il faudrait rajouter ceci pour activer la prise en charge de TS dans ce fichier
```suggestion
<script lang="ts">
```

2022-05-10 09:22 UTC, Volubyl commented on client/src/lib/components/DatasetFormLayout/DatasetFormLayout.svelte
> +  let anchors = [];
```suggestion
  let anchors: string[] = [];
```

2022-05-10 11:39 UTC, lpoujade commented on client/src/lib/components/DatasetFormLayout/DatasetFormLayout.svelte
>  <script>
ah oui mon linter est beaucoup plus bavard d'un coup :smile:

2022-05-10 12:51 UTC, lpoujade commented
C'est corrigé ! Les erreurs reportés par `make check` venait probablement de l'absence de typage, je ne vois pas de différences avec `master` maintenant

2022-05-11 10:42 UTC, florimondmanca commented
Hmm, la CI n'a pas l'air de se lancer. Je ne suis pas encore au clair avec les nouvelles règles de GitHub concernant les "contributeurs extérieurs"... D'habitude, un bouton "Approve and Run" apparaît, ici il n'y en a pas. https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork Il y a peut-être des règles supplémentaires au niveau de l'org `etalab`. Je regarde...

2022-05-11 10:58 UTC, florimondmanca commented
Arf, malgré #231, les runs manuels ne semblent pas permis sur les forks.

@lpoujade J'ai modifié un paramètre pour ne requérir d'approbation (qui ne s'est pas montrée ici...) que pour les nouveaux utilisateurs GitHub. Tu devrais donc en être exempté. Mais je fais l'hypothèse qu'il faut créer une nouvelle PR pour que les changements s'appliquent...

Je vais essayer de fermer et rouvrir cette PR, et si la CI ne se lance toujours pas, pourras-tu essayer de créer une nouvelle PR de ton côté ?

Désolé pour ce contre-temps. Tu fais les frais de la première contribution extérieure ! :-)

2022-05-11 11:52 UTC, lpoujade commented
> Tu fais les frais de la première contribution extérieure ! :-)

Avec plaisir ! 😄

Je vois pas bien sur mobile, la ci est passée et sans erreurs ?

Le 11 mai 2022 12:58:56 GMT+02:00, Florimond Manca ***@***.***> a écrit :
>Arf, malgré #231, les runs manuels ne semblent pas permis sur les forks.
>
>
>
***@***.*** J'ai modifié un paramètre pour ne requérir d'approbation (qui ne s'est pas montrée ici...) que pour les nouveaux utilisateurs GitHub. Tu devrais donc en être exempté. Mais je fais l'hypothèse qu'il faut créer une nouvelle PR pour que les changements s'appliquent...
>
>
>
>Je vais essayer de fermer et rouvrir cette PR, et si la CI ne se lance toujours pas, pourras-tu essayer de créer une nouvelle PR de ton côté ?
>
>
>
>Désolé pour ce contre-temps. Tu fais les frais de la première contribution extérieure ! :-)
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/etalab/catalogage-donnees/pull/228#issuecomment-1123577518
>
>You are receiving this because you were mentioned.
>
>
>
>Message ID: ***@***.***>

2022-05-11 13:12 UTC, florimondmanca commented
@lpoujade Oui, la CI est :green_circle:. :+1:

2022-05-11 13:15 UTC, florimondmanca reviewed
J'ai testé en local : ça fonctionne, merci !

J'ai laissé quelques commentaires à adresser pour la qualité du code.

Il faudrait idéalement ajouter un petit test E2E. Mais comme le refacto que je propose dans un de mes commentaires, on peut le faire nous-mêmes dans une PR complémentaire.

2022-05-12 07:17 UTC, lpoujade commented
Merci pour ce retour détaillé ! :)

Je peux proposer une autre pr mais je n'aurais pas le temps avant la semaine prochaine

Pour les check des variables indéfinies ils sont effectivement inutiles, tel quel le linter ne les acceptait pas

Pour le padding c'est parce que la hauteur de la page ne permet pas de détecter la dernière ancre, elle est donc affiché lorsqu'on est tout en bas, mais sans ce padding c'est celle du dessus qui n'est pas détecté

Pour la supposition des ancres dans le bon sens j'ai effectivement fait confiance aux dev de svelte qui l'ont fait comme ça pour leur guide :)

Le 11 mai 2022 15:16:09 GMT+02:00, Florimond Manca ***@***.***> a écrit :
***@***.*** commented on this pull request.
>
>
>
>J'ai testé en local : ça fonctionne, merci !
>
>
>
>J'ai laissé quelques commentaires à adresser pour la qualité du code.
>
>
>
>Il faudrait idéalement ajouter un petit test E2E. Mais comme le refacto que je propose dans un de mes commentaires, on peut le faire nous-mêmes dans une PR complémentaire.
>
>
>
>>    let segment = "";
>
>+
>
>+  let container: Element | undefined = undefined;
>
>
>
>(Nit) Cette variable peut-elle effectivement être `undefined` en pratique ?
>
>
>
>D'après la [documentation de `bind:this`](https://svelte.dev/docs#template-syntax-element-directives-bind-this), la cible est définie dès le `onMount()`, et a fortiori dans les fonctions suivantes.
>
>
>
>Ça nous économiserait des assertions de type, et donc de retirer les `if (... === undefined)`.
>
>
>
>En suivant cette doc, il semble qu'on puisse faire directement:
>
>
>
>```ts
>
>let container: Element:
>
>```
>
>
>
>> +    if (anchors === undefined || positions === undefined) return;
>
>+
>
>
>
>(Nit) Inutile car `positions` et `anchors` sont bien initialisées à `[]`, n'est-ce pas ?
>
>
>
>```suggestion
>
>```
>
>
>
>> +    if (window.innerHeight + window.pageYOffset >= document.body.offsetHeight) {
>
>+      // scrolled to bottom
>
>+      segment = anchors[anchors.length - 1].id;
>
>
>
>(Nit) Pour la lisibilité, on peut utiliser des variables nommées descriptives ici, ce qui permet d'ailleurs de retirer le commentaire qui sert pour l'instant cette fonction d'aide à la lecture. Par exemple :
>
>
>
>```suggestion
>
>    const hasReachedBottom = (
>
>      window.innerHeight + window.pageYOffset >= document.body.offsetHeight
>
>    );
>
>
>
>    if (hasReachedBottom) {
>
>      const lastSegment = anchors[anchors.length - 1];
>
>      segment = lastSegment.id;
>
>```
>
>
>
>> +    let i = anchors.length;
>
>+    let lastId = "";
>
>+    while (i--) {
>
>+      if (positions[i] - top < 40) {
>
>+        const { id } = anchors[i];
>
>+
>
>+        if (id !== lastId) {
>
>+          segment = id;
>
>+          lastId = id;
>
>+        }
>
>+        return;
>
>+      }
>
>+    }
>
>
>
>Ce code est correct, mais j'ai eu beaucoup de mal à comprendre ce qu'il faisait.
>
>
>
>Je proposerai un refactor dans une PR suivante, je pense, car pouvoir passer de ce "while à l'envers qui suppose que `anchors` soit trié dans le bon sens" à quelque chose qui utilise les fonctions array type `.filter()` et des variables descriptives, il faudrait modifier le modèle de données.
>
>
>
>> +    container.querySelectorAll("h2").forEach((anchor) => {
>
>+      if (anchor.id !== "") anchors.push(anchor);
>
>+    });
>
>
>
>(Tip) On dirait que le check sur `anchor.id` vient du fait que le `<h2>` pour les mots-clés n'a pas de `id`.
>
>
>
>Je ne sais pas si c'est voulu. Pour l'heure, on peut aussi passer ce check dans le sélecteur CSS :
>
>
>
>```suggestion
>
>    container.querySelectorAll("h2[id]").forEach((anchor) => {
>
>      anchors.push(anchor);
>
>    });
>
>```
>
>
>
>> +
>
>+  #ouverture {
>
>+    padding-top: 10px;
>
>+  }
>
>
>
>Cet ajout de padding ne semble pas souhaitable, puisqu'on gère déjà les paddings via des classes CSS du design system conformément à notre maquette.
>
>
>
>Si on le retire, le suivi au scroll continue de fonctionner, donc je propose de l'enlever :
>
>
>
>```suggestion
>
>```
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/etalab/catalogage-donnees/pull/228#pullrequestreview-969217768
>
>You are receiving this because you were mentioned.
>
>
>
>Message ID: ***@***.***>

2022-05-16 07:57 UTC, Volubyl commented
@lpoujade pour ma part je trouverai ça cool que t'ailles au bout du truc donc non, au contraire, n'hésites pas à proposer d'autres modifs!

Merci à toi

2022-05-18 07:37 UTC, lpoujade commented on client/src/lib/components/DatasetForm/DatasetForm.svelte
> +  }
Je l'ai enlevé mais étant donné que les deux blocs ne prennent qu'un seul écran, je n'ai pas réussi a trouver un comportement vraiment cohérent sans ajouter cet espace. La seule autre solution que je vois serait de désactiver le scroll par défaut au click sur les link, et de faire le scroll puis le changement de highlight "a la main" sur un clic handler sur chaque lien, ce que je trouve un peu lourd

2022-05-23 09:28 UTC, florimondmanca reviewed
Merci de la mise à jour, je viens de tester en local, ça fonctionne du tonnerre :zap:

J'ai laissé un commentaire sur comment on pourrait améliorer la partie test e2e, c'est-à-dire pour détecter avec plus de rigueurs d'éventuelles régressions

2022-05-23 09:28 UTC, florimondmanca commented on client/src/tests/e2e/contribuer.spec.ts
> +    ).toHaveAttribute("aria-current", "page");
(Nit) Pour une raison de découplage des tests, et pour se permettre un testing plus exhaustif, peut-être vaudrait-il mieux avoir un test spécifique `test("Sees sidebar active item change as page scrolls")` ?

Avec Playwright, on peut s'aider de la méthode `.focus()` : https://playwright.dev/docs/api/class-elementhandle#element-handle-focus

Il me semble qu'il faudrait tester ces cas :

- Initialement, "Informations générales" est actif
- Scroll tout en bas de la page : "Ouverture" devient actif
- Scroll vers une section particulière (`focus()` par son `id`) : la section en question devient active
- Scroll vers un champ sous une section particulière : la section auquel il appartient devient active

2022-05-30 08:53 UTC, florimondmanca approved these changes
C'est OK pour moi, je vais merger et on peut traiter ma suggestion d'amélioration du test E2E dans une autre PR (je vais probablement m'en occuper dans la foulée)

Merci beaucoup à toi @lpoujade à nouveau !

2022-05-30 09:03 UTC, merged

2022-05-30 14:47 UTC, lpoujade commented
Avec plaisir :)

J'avais commencé a adapter les tests mais sans succès, ça ne donne pas tjrs le même résultat (je suppose que le framework teste différents types de fenêtres) ; et comme je disais, je n'ai pas réussi a avoir un comportement parfait sans le padding (test de cliquer sur "mise a jour", ça ne fonctionne pas vraiment parfaitement)

Le 30 mai 2022 11:03:35 GMT+02:00, Florimond Manca ***@***.***> a écrit :
>Merged #228 into master.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/etalab/catalogage-donnees/pull/228#event-6701204086
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

2022-05-30 15:24 UTC, florimondmanca commented
@lpoujade Oui en effet il y a une sorte de conflit entre la stratégie générale (activer l'item s'il remonte assez haut dans la page) et le cas particulier de "Ouverture" (si on atteint le bas de la page, activer le dernier item). Je ne suis moi-même pas sûr de ce qu'il devrait se passer quand on clique sur "Mise à jour"... Pour l'instant le comportement semble "good enough" : https://demo.catalogue.multi.coop/contribuer